"""Declarative models mirroring the existing SQLite schema.

GENERATED by scripts/generate_models.py from data/earnings_ml.db.
Do not add columns here without a matching migration in migrations.py.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import Integer, REAL, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class AdoptedPosition(Base):
    __tablename__ = 'adopted_positions'
    symbol: Mapped[Optional[str]] = mapped_column(Text, primary_key=True)
    adopted_at: Mapped[str] = mapped_column(Text, nullable=False)


class AlpacaPosition(Base):
    __tablename__ = 'alpaca_positions'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False)
    symbol: Mapped[Optional[str]] = mapped_column(Text)
    qty: Mapped[Optional[float]] = mapped_column(REAL)
    side: Mapped[Optional[str]] = mapped_column(Text)
    avg_entry_price: Mapped[Optional[float]] = mapped_column(REAL)
    current_price: Mapped[Optional[float]] = mapped_column(REAL)
    market_value: Mapped[Optional[float]] = mapped_column(REAL)
    unrealized_pl: Mapped[Optional[float]] = mapped_column(REAL)
    strategy: Mapped[Optional[str]] = mapped_column(Text)
    managed: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    run_id: Mapped[Optional[int]] = mapped_column(Integer)


class CalendarCallTrade(Base):
    __tablename__ = 'calendar_call_trades'
    snapshot_id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    earnings_date: Mapped[str] = mapped_column(Text, nullable=False)
    scan_date: Mapped[str] = mapped_column(Text, nullable=False)
    near_expiry: Mapped[str] = mapped_column(Text, nullable=False)
    far_expiry: Mapped[str] = mapped_column(Text, nullable=False)
    strike: Mapped[float] = mapped_column(REAL, nullable=False)
    near_call_ticker: Mapped[str] = mapped_column(Text, nullable=False)
    far_call_ticker: Mapped[str] = mapped_column(Text, nullable=False)
    near_entry: Mapped[float] = mapped_column(REAL, nullable=False)
    far_entry: Mapped[float] = mapped_column(REAL, nullable=False)
    near_exit: Mapped[float] = mapped_column(REAL, nullable=False)
    far_exit: Mapped[float] = mapped_column(REAL, nullable=False)
    net_debit: Mapped[float] = mapped_column(REAL, nullable=False)
    exit_value: Mapped[float] = mapped_column(REAL, nullable=False)
    pnl_dollars: Mapped[float] = mapped_column(REAL, nullable=False)
    return_on_debit: Mapped[Optional[float]] = mapped_column(REAL)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=text('CURRENT_TIMESTAMP'))
    model_score: Mapped[Optional[float]] = mapped_column(REAL)
    model_recommendation: Mapped[Optional[int]] = mapped_column(Integer)
    model_reason: Mapped[Optional[str]] = mapped_column(Text)
    model_name: Mapped[Optional[str]] = mapped_column(Text)
    model_scored_at: Mapped[Optional[str]] = mapped_column(Text)


class DailySignal(Base):
    __tablename__ = 'daily_signals'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    signal_date: Mapped[str] = mapped_column(Text, nullable=False)
    option_volume: Mapped[Optional[float]] = mapped_column(REAL)
    atm_iv: Mapped[Optional[float]] = mapped_column(REAL)
    skew_25d: Mapped[Optional[float]] = mapped_column(REAL)
    skew_zscore: Mapped[Optional[float]] = mapped_column(REAL)
    skew_mean: Mapped[Optional[float]] = mapped_column(REAL)
    iv_pctl_1y: Mapped[Optional[float]] = mapped_column(REAL)
    ts_momentum: Mapped[Optional[float]] = mapped_column(REAL)
    relative_momentum: Mapped[Optional[float]] = mapped_column(REAL)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))


class DataCatalog(Base):
    __tablename__ = 'data_catalog'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    dataset: Mapped[str] = mapped_column(Text, nullable=False)
    symbol: Mapped[Optional[str]] = mapped_column(Text)
    as_of_date: Mapped[Optional[str]] = mapped_column(Text)
    available_at: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    pit_safe: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('1'))
    ingested_at: Mapped[str] = mapped_column(Text, nullable=False)


class EquitySnapshot(Base):
    __tablename__ = 'equity_snapshots'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False)
    equity: Mapped[Optional[float]] = mapped_column(REAL)
    buying_power: Mapped[Optional[float]] = mapped_column(REAL)
    portfolio_value: Mapped[Optional[float]] = mapped_column(REAL)
    source: Mapped[Optional[str]] = mapped_column(Text, server_default=text("'alpaca'"))


class ExitProposal(Base):
    __tablename__ = 'exit_proposals'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[str] = mapped_column(Text, nullable=False)
    group_id: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[str] = mapped_column(Text, nullable=False)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    rule: Mapped[str] = mapped_column(Text, nullable=False)
    reason: Mapped[Optional[str]] = mapped_column(Text)
    card_text: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    snoozed_until: Mapped[Optional[str]] = mapped_column(Text)
    decided_by: Mapped[Optional[int]] = mapped_column(Integer)
    decided_at: Mapped[Optional[str]] = mapped_column(Text)


class FfLadder(Base):
    __tablename__ = 'ff_ladders'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    candidate_json: Mapped[str] = mapped_column(Text, nullable=False)
    order_id: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'armed'"))
    rung: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    armed_by: Mapped[Optional[int]] = mapped_column(Integer)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))
    updated_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))


class FfSnapshot(Base):
    __tablename__ = 'ff_snapshots'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    scan_date: Mapped[str] = mapped_column(Text, nullable=False)
    earnings_date: Mapped[str] = mapped_column(Text, nullable=False)
    spot: Mapped[Optional[float]] = mapped_column(REAL)
    t1_expiry: Mapped[Optional[str]] = mapped_column(Text)
    t1_dte: Mapped[Optional[int]] = mapped_column(Integer)
    t1_strike: Mapped[Optional[float]] = mapped_column(REAL)
    t1_contract: Mapped[Optional[str]] = mapped_column(Text)
    t1_close: Mapped[Optional[float]] = mapped_column(REAL)
    t1_iv: Mapped[Optional[float]] = mapped_column(REAL)
    t2_expiry: Mapped[Optional[str]] = mapped_column(Text)
    t2_dte: Mapped[Optional[int]] = mapped_column(Integer)
    t2_strike: Mapped[Optional[float]] = mapped_column(REAL)
    t2_contract: Mapped[Optional[str]] = mapped_column(Text)
    t2_close: Mapped[Optional[float]] = mapped_column(REAL)
    t2_iv: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_fwd: Mapped[Optional[float]] = mapped_column(REAL)
    tau_days: Mapped[Optional[int]] = mapped_column(Integer)
    implied_event_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    hist_median_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    n_hist_events: Mapped[Optional[int]] = mapped_column(Integer)
    premium_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    skip_reason: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))
    hist_rms_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    selector_version: Mapped[Optional[int]] = mapped_column(Integer)


class FfUniverseSnapshot(Base):
    __tablename__ = 'ff_universe_snapshots'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    scan_date: Mapped[str] = mapped_column(Text, nullable=False)
    has_earnings_in_window: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    earnings_date: Mapped[Optional[str]] = mapped_column(Text)
    spot: Mapped[Optional[float]] = mapped_column(REAL)
    t1_expiry: Mapped[Optional[str]] = mapped_column(Text)
    t1_dte: Mapped[Optional[int]] = mapped_column(Integer)
    t1_strike: Mapped[Optional[float]] = mapped_column(REAL)
    t1_contract: Mapped[Optional[str]] = mapped_column(Text)
    t1_close: Mapped[Optional[float]] = mapped_column(REAL)
    t1_iv: Mapped[Optional[float]] = mapped_column(REAL)
    t2_expiry: Mapped[Optional[str]] = mapped_column(Text)
    t2_dte: Mapped[Optional[int]] = mapped_column(Integer)
    t2_strike: Mapped[Optional[float]] = mapped_column(REAL)
    t2_contract: Mapped[Optional[str]] = mapped_column(Text)
    t2_close: Mapped[Optional[float]] = mapped_column(REAL)
    t2_iv: Mapped[Optional[float]] = mapped_column(REAL)
    forward_factor: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_fwd: Mapped[Optional[float]] = mapped_column(REAL)
    tau_days: Mapped[Optional[int]] = mapped_column(Integer)
    implied_event_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    hist_median_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    n_hist_events: Mapped[Optional[int]] = mapped_column(Integer)
    premium_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    skip_reason: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))
    hist_rms_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    selector_version: Mapped[Optional[int]] = mapped_column(Integer)


class JobRun(Base):
    __tablename__ = 'job_runs'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    job_name: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[str] = mapped_column(Text, nullable=False)
    finished_at: Mapped[Optional[str]] = mapped_column(Text)
    success: Mapped[Optional[int]] = mapped_column(Integer)
    stats_json: Mapped[Optional[str]] = mapped_column(Text)
    error: Mapped[Optional[str]] = mapped_column(Text)


class LiveCalendarCandidate(Base):
    __tablename__ = 'live_calendar_candidates'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scan_timestamp: Mapped[str] = mapped_column(Text, nullable=False)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    earnings_date: Mapped[Optional[str]] = mapped_column(Text)
    price: Mapped[Optional[float]] = mapped_column(REAL)
    strike: Mapped[Optional[float]] = mapped_column(REAL)
    near_expiry: Mapped[Optional[str]] = mapped_column(Text)
    far_expiry: Mapped[Optional[str]] = mapped_column(Text)
    near_bid: Mapped[Optional[float]] = mapped_column(REAL)
    near_ask: Mapped[Optional[float]] = mapped_column(REAL)
    far_bid: Mapped[Optional[float]] = mapped_column(REAL)
    far_ask: Mapped[Optional[float]] = mapped_column(REAL)
    near_entry: Mapped[Optional[float]] = mapped_column(REAL)
    far_entry: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_bid: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_mid: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_ask: Mapped[Optional[float]] = mapped_column(REAL)
    model_expected_return: Mapped[Optional[float]] = mapped_column(REAL)
    model_decision: Mapped[Optional[str]] = mapped_column(Text)
    model_rejection_reasons: Mapped[Optional[str]] = mapped_column(Text)
    selected_by_bot: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    features_json: Mapped[Optional[str]] = mapped_column(Text)
    exit_value: Mapped[Optional[float]] = mapped_column(REAL)
    pnl_dollars: Mapped[Optional[float]] = mapped_column(REAL)
    return_on_debit: Mapped[Optional[float]] = mapped_column(REAL)
    outcome_fetched_at: Mapped[Optional[str]] = mapped_column(Text)
    tier: Mapped[Optional[int]] = mapped_column(Integer)
    passed: Mapped[Optional[int]] = mapped_column(Integer)
    near_miss: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    scanner_reason: Mapped[Optional[str]] = mapped_column(Text)
    display_status: Mapped[Optional[str]] = mapped_column(Text)
    volume: Mapped[Optional[float]] = mapped_column(REAL)
    market_cap: Mapped[Optional[float]] = mapped_column(REAL)
    days_to_expiry: Mapped[Optional[int]] = mapped_column(Integer)
    total_open_interest: Mapped[Optional[int]] = mapped_column(Integer)
    atm_iv_near: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_baseline_1y: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg_fair: Mapped[Optional[float]] = mapped_column(REAL)
    actual_to_fair_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    iv_rv_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    hist_vol_3m: Mapped[Optional[float]] = mapped_column(REAL)
    term_slope: Mapped[Optional[float]] = mapped_column(REAL)
    term_structure_valid: Mapped[Optional[int]] = mapped_column(Integer)
    expected_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    expected_move_dollars: Mapped[Optional[float]] = mapped_column(REAL)
    straddle_price: Mapped[Optional[float]] = mapped_column(REAL)
    atm_call_delta: Mapped[Optional[float]] = mapped_column(REAL)
    atm_put_delta: Mapped[Optional[float]] = mapped_column(REAL)
    atm_call_iv: Mapped[Optional[float]] = mapped_column(REAL)
    atm_put_iv: Mapped[Optional[float]] = mapped_column(REAL)
    win_rate: Mapped[Optional[float]] = mapped_column(REAL)
    win_quarters: Mapped[Optional[int]] = mapped_column(Integer)
    pre_earnings_close: Mapped[Optional[float]] = mapped_column(REAL)
    post_earnings_close: Mapped[Optional[float]] = mapped_column(REAL)
    actual_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    actual_move_direction: Mapped[Optional[str]] = mapped_column(Text)
    max_intraday_range_pct: Mapped[Optional[float]] = mapped_column(REAL)
    outcome_attempt_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))


class ManagedPosition(Base):
    __tablename__ = 'managed_positions'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[str] = mapped_column(Text, nullable=False)
    group_id: Mapped[Optional[str]] = mapped_column(Text)
    qty: Mapped[float] = mapped_column(REAL, nullable=False)
    entry_price: Mapped[Optional[float]] = mapped_column(REAL)
    exit_price: Mapped[Optional[float]] = mapped_column(REAL)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'open'"))
    order_id: Mapped[Optional[str]] = mapped_column(Text)
    opened_at: Mapped[str] = mapped_column(Text, nullable=False)
    closed_at: Mapped[Optional[str]] = mapped_column(Text)
    metadata_: Mapped[Optional[str]] = mapped_column('metadata', Text)
    exit_by: Mapped[Optional[str]] = mapped_column(Text)


class ModelRegistry(Base):
    __tablename__ = 'model_registry'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    sha256: Mapped[str] = mapped_column(Text, nullable=False)
    trained_at: Mapped[Optional[str]] = mapped_column(Text)
    promoted_at: Mapped[Optional[str]] = mapped_column(Text)


class OptionsChain(Base):
    __tablename__ = 'options_chain'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    collector_run_id: Mapped[Optional[str]] = mapped_column(Text)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    scan_date: Mapped[str] = mapped_column(Text, nullable=False)
    contract_ticker: Mapped[str] = mapped_column(Text, nullable=False)
    underlying: Mapped[Optional[str]] = mapped_column(Text)
    expiry: Mapped[Optional[str]] = mapped_column(Text)
    strike: Mapped[Optional[float]] = mapped_column(REAL)
    contract_type: Mapped[Optional[str]] = mapped_column(Text)
    style: Mapped[Optional[str]] = mapped_column(Text)
    bid: Mapped[Optional[float]] = mapped_column(REAL)
    ask: Mapped[Optional[float]] = mapped_column(REAL)
    bid_size: Mapped[Optional[int]] = mapped_column(Integer)
    ask_size: Mapped[Optional[int]] = mapped_column(Integer)
    midpoint: Mapped[Optional[float]] = mapped_column(REAL)
    close: Mapped[Optional[float]] = mapped_column(REAL)
    open_price: Mapped[Optional[float]] = mapped_column(REAL)
    high: Mapped[Optional[float]] = mapped_column(REAL)
    low: Mapped[Optional[float]] = mapped_column(REAL)
    trade_count: Mapped[Optional[int]] = mapped_column(Integer)
    volume: Mapped[Optional[int]] = mapped_column(Integer)
    vwap: Mapped[Optional[float]] = mapped_column(REAL)
    implied_volatility: Mapped[Optional[float]] = mapped_column(REAL)
    delta: Mapped[Optional[float]] = mapped_column(REAL)
    gamma: Mapped[Optional[float]] = mapped_column(REAL)
    theta: Mapped[Optional[float]] = mapped_column(REAL)
    vega: Mapped[Optional[float]] = mapped_column(REAL)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))
    captured_at: Mapped[Optional[str]] = mapped_column(Text)
    captured_hour: Mapped[Optional[str]] = mapped_column(Text)


class PendingTrade(Base):
    __tablename__ = 'pending_trades'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[str] = mapped_column(Text, nullable=False)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    side: Mapped[str] = mapped_column(Text, nullable=False)
    trade_json: Mapped[str] = mapped_column(Text, nullable=False)
    card_text: Mapped[str] = mapped_column(Text, nullable=False)
    model_score: Mapped[Optional[float]] = mapped_column(REAL)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    order_json: Mapped[Optional[str]] = mapped_column(Text)
    note: Mapped[Optional[str]] = mapped_column(Text)
    decided_by: Mapped[Optional[int]] = mapped_column(Integer)
    decided_at: Mapped[Optional[str]] = mapped_column(Text)


class Pick(Base):
    __tablename__ = 'picks'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    pick_date: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[str] = mapped_column(Text, nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    signals_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))


class ProposalFunnel(Base):
    __tablename__ = 'proposal_funnel'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    created_at: Mapped[str] = mapped_column(Text, nullable=False)
    strategies: Mapped[str] = mapped_column(Text, nullable=False)
    counts: Mapped[str] = mapped_column(Text, nullable=False)
    proposals_total: Mapped[int] = mapped_column(Integer, nullable=False)


class RiskEvent(Base):
    __tablename__ = 'risk_events'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[Optional[str]] = mapped_column(Text)
    detail: Mapped[Optional[str]] = mapped_column(Text)


class RiskState(Base):
    __tablename__ = 'risk_state'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    halted: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text('0'))
    reason: Mapped[Optional[str]] = mapped_column(Text)
    tripped_at: Mapped[Optional[str]] = mapped_column(Text)
    tripped_by: Mapped[Optional[str]] = mapped_column(Text)


class ScanRun(Base):
    __tablename__ = 'scan_runs'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scan_timestamp: Mapped[str] = mapped_column(Text, nullable=False)
    scanner_name: Mapped[str] = mapped_column(Text, nullable=False)
    trigger_type: Mapped[str] = mapped_column(Text, nullable=False)
    candidate_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    tier1_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    tier2_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    take_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    duration_secs: Mapped[Optional[float]] = mapped_column(REAL)
    success: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text, server_default=text("datetime('now')"))


class ScannerScanOutput(Base):
    __tablename__ = 'scanner_scan_outputs'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    scan_timestamp: Mapped[str] = mapped_column(Text, nullable=False)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    earnings_date: Mapped[Optional[str]] = mapped_column(Text)
    tier: Mapped[Optional[int]] = mapped_column(Integer)
    passed: Mapped[Optional[int]] = mapped_column(Integer)
    near_miss: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    scanner_reason: Mapped[Optional[str]] = mapped_column(Text)
    display_status: Mapped[Optional[str]] = mapped_column(Text)
    price: Mapped[Optional[float]] = mapped_column(REAL)
    volume: Mapped[Optional[float]] = mapped_column(REAL)
    market_cap: Mapped[Optional[float]] = mapped_column(REAL)
    strike: Mapped[Optional[float]] = mapped_column(REAL)
    near_expiry: Mapped[Optional[str]] = mapped_column(Text)
    far_expiry: Mapped[Optional[str]] = mapped_column(Text)
    days_to_expiry: Mapped[Optional[int]] = mapped_column(Integer)
    total_open_interest: Mapped[Optional[int]] = mapped_column(Integer)
    net_debit: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_bid: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_mid: Mapped[Optional[float]] = mapped_column(REAL)
    net_debit_ask: Mapped[Optional[float]] = mapped_column(REAL)
    atm_iv_near: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_baseline_1y: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg_fair: Mapped[Optional[float]] = mapped_column(REAL)
    actual_to_fair_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    iv_rv_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    term_slope: Mapped[Optional[float]] = mapped_column(REAL)
    term_structure_valid: Mapped[Optional[int]] = mapped_column(Integer)
    expected_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    expected_move_dollars: Mapped[Optional[float]] = mapped_column(REAL)
    win_rate: Mapped[Optional[float]] = mapped_column(REAL)
    win_quarters: Mapped[Optional[int]] = mapped_column(Integer)
    model_expected_return: Mapped[Optional[float]] = mapped_column(REAL)
    model_decision: Mapped[Optional[str]] = mapped_column(Text)
    model_rejection_reasons: Mapped[Optional[str]] = mapped_column(Text)
    selected_by_bot: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    features_json: Mapped[Optional[str]] = mapped_column(Text)
    exit_value: Mapped[Optional[float]] = mapped_column(REAL)
    pnl_dollars: Mapped[Optional[float]] = mapped_column(REAL)
    return_on_debit: Mapped[Optional[float]] = mapped_column(REAL)
    outcome_fetched_at: Mapped[Optional[str]] = mapped_column(Text)


class Snapshot(Base):
    __tablename__ = 'snapshots'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(Text, nullable=False)
    earnings_date: Mapped[str] = mapped_column(Text, nullable=False)
    scan_date: Mapped[str] = mapped_column(Text, nullable=False)
    timing: Mapped[Optional[str]] = mapped_column(Text)
    price: Mapped[Optional[float]] = mapped_column(REAL)
    avg_volume_30d: Mapped[Optional[float]] = mapped_column(REAL)
    market_cap: Mapped[Optional[float]] = mapped_column(REAL)
    has_options: Mapped[Optional[int]] = mapped_column(Integer)
    nearest_expiry: Mapped[Optional[str]] = mapped_column(Text)
    days_to_expiry: Mapped[Optional[int]] = mapped_column(Integer)
    total_open_interest: Mapped[Optional[int]] = mapped_column(Integer)
    atm_iv_near: Mapped[Optional[float]] = mapped_column(REAL)
    rv30: Mapped[Optional[float]] = mapped_column(REAL)
    iv30_rv30: Mapped[Optional[float]] = mapped_column(REAL)
    hist_vol_3m: Mapped[Optional[float]] = mapped_column(REAL)
    term_slope: Mapped[Optional[float]] = mapped_column(REAL)
    term_structure_valid: Mapped[Optional[int]] = mapped_column(Integer)
    expected_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    expected_move_dollars: Mapped[Optional[float]] = mapped_column(REAL)
    straddle_price: Mapped[Optional[float]] = mapped_column(REAL)
    atm_call_delta: Mapped[Optional[float]] = mapped_column(REAL)
    atm_put_delta: Mapped[Optional[float]] = mapped_column(REAL)
    atm_call_iv: Mapped[Optional[float]] = mapped_column(REAL)
    atm_put_iv: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_baseline_1y: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg: Mapped[Optional[float]] = mapped_column(REAL)
    sigma_short_leg_fair: Mapped[Optional[float]] = mapped_column(REAL)
    actual_to_fair_ratio: Mapped[Optional[float]] = mapped_column(REAL)
    recommendation: Mapped[Optional[str]] = mapped_column(Text)
    mc_win_rate: Mapped[Optional[float]] = mapped_column(REAL)
    mc_quarters: Mapped[Optional[int]] = mapped_column(Integer)
    collection_error: Mapped[Optional[str]] = mapped_column(Text)
    pre_earnings_close: Mapped[Optional[float]] = mapped_column(REAL)
    post_earnings_close: Mapped[Optional[float]] = mapped_column(REAL)
    actual_move_pct: Mapped[Optional[float]] = mapped_column(REAL)
    actual_move_direction: Mapped[Optional[str]] = mapped_column(Text)
    max_intraday_range_pct: Mapped[Optional[float]] = mapped_column(REAL)
    outcome_fetched_at: Mapped[Optional[str]] = mapped_column(Text)
    outcome_attempt_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    data_source: Mapped[Optional[str]] = mapped_column(Text, server_default=text('"unknown"'))


class StrategyState(Base):
    __tablename__ = 'strategy_state'
    name: Mapped[Optional[str]] = mapped_column(Text, primary_key=True)
    lifecycle: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'paper'"))
    updated_at: Mapped[Optional[str]] = mapped_column(Text)
    updated_by: Mapped[Optional[str]] = mapped_column(Text)
    enabled: Mapped[Optional[int]] = mapped_column(Integer)
    execution_mode: Mapped[Optional[str]] = mapped_column(Text)


class TradeEvent(Base):
    __tablename__ = 'trade_events'
    id: Mapped[Optional[int]] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    symbol: Mapped[Optional[str]] = mapped_column(Text)
    strategy: Mapped[Optional[str]] = mapped_column(Text)
    qty: Mapped[Optional[float]] = mapped_column(REAL)
    price: Mapped[Optional[float]] = mapped_column(REAL)
    detail: Mapped[Optional[str]] = mapped_column(Text)
