#!/usr/bin/env python3
"""Generate earnings_edge/db/models.py from the live SQLite schema.

One-shot dev tool: reads data/earnings_ml.db, emits declarative models that
mirror the existing schema exactly (same names/types/pk, defaults preserved).
"""
from pathlib import Path

from sqlalchemy import create_engine, text

DB = Path(__file__).resolve().parent.parent / "data" / "earnings_ml.db"
OUT = Path(__file__).resolve().parent.parent / "earnings_edge" / "db" / "models.py"

CLASS_NAMES = {
    "adopted_positions": "AdoptedPosition",
    "alpaca_positions": "AlpacaPosition",
    "calendar_call_trades": "CalendarCallTrade",
    "daily_signals": "DailySignal",
    "data_catalog": "DataCatalog",
    "equity_snapshots": "EquitySnapshot",
    "exit_proposals": "ExitProposal",
    "ff_ladders": "FfLadder",
    "ff_snapshots": "FfSnapshot",
    "job_runs": "JobRun",
    "live_calendar_candidates": "LiveCalendarCandidate",
    "managed_positions": "ManagedPosition",
    "model_registry": "ModelRegistry",
    "options_chain": "OptionsChain",
    "pending_trades": "PendingTrade",
    "picks": "Pick",
    "proposal_funnel": "ProposalFunnel",
    "risk_events": "RiskEvent",
    "risk_state": "RiskState",
    "scan_runs": "ScanRun",
    "scanner_scan_outputs": "ScannerScanOutput",
    "snapshots": "Snapshot",
    "strategy_state": "StrategyState",
    "trade_events": "TradeEvent",
}

PY_TYPES = {"TEXT": ("Optional[str]", "Text"), "INTEGER": ("Optional[int]", "Integer"),
            "REAL": ("Optional[float]", "REAL")}

HEADER = '''"""Declarative models mirroring the existing SQLite schema.

GENERATED by scripts/generate_models.py from data/earnings_ml.db.
Do not add columns here without a matching migration in migrations.py.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import Integer, REAL, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass
'''


def py_type(sql_type: str, notnull: int) -> str:
    opt, _ = PY_TYPES[sql_type.upper()]
    if notnull:
        return opt.replace("Optional[", "", 1).rstrip("]") if opt.startswith("Optional[") else opt
    return opt


def main() -> None:
    # Direct engine (no configure()) so introspection never writes schema.
    eng = create_engine(f"sqlite:///{DB}")
    with eng.connect() as con:
        tables = [r[0] for r in con.execute(text(
            "SELECT name FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence' ORDER BY name"))]
        parts = [HEADER]
        for t in tables:
            parts.append(f"\n\nclass {CLASS_NAMES[t]}(Base):\n    __tablename__ = {t!r}\n")
            for cid, name, typ, notnull, dflt, pk in con.execute(text(f'PRAGMA table_info("{t}")')):
                ann = py_type(typ or "TEXT", notnull and not pk)
                _, sa_type = PY_TYPES[(typ or "TEXT").upper()]
                args = []
                attr = name
                if name == "metadata":  # clashes with Base.metadata
                    attr = "metadata_"
                    args.append(repr(name))
                args.append(sa_type)
                if pk:
                    args.append("primary_key=True")
                    if (typ or "").upper() == "INTEGER":
                        args.append("autoincrement=True")
                if notnull and not pk:
                    args.append("nullable=False")
                if dflt is not None:
                    # PRAGMA dflt_value is already the verbatim SQL literal
                    # ('pending', CURRENT_TIMESTAMP, 0, datetime('now')), so always
                    # wrap in text() — never re-quote it as a Python string.
                    args.append(f"server_default=text({str(dflt)!r})")
                parts.append(f"    {attr}: Mapped[{ann}] = mapped_column({', '.join(args)})\n")
    OUT.write_text("".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
